version: "3.9"

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    image: dropshare-server
    container_name: dropshare-node-server
    command: yarn dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    restart: always
    image: mongo:4.0
    container_name: dropshare-mongo
    volumes:
      - ~/Volumes/dropshare-mongo-4.0:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    image: dropshare-client
    container_name: dropshare-react-client
    command: yarn dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
