version: "3.9"

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    image: dropshare-server
    container_name: dropshare-node-server
    command: yarn dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    expose: [80]
  mongo:
    restart: always
    image: mongo:4.0
    container_name: dropshare-mongo
    volumes:
      - ~/Volumes/dropshare-mongo-4.0:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
